<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class SimulationResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'first_name' => $this->first_name,
            'last_name' => $this->last_name,
            'email' => $this->email,
            'sim_token' => $this->uuid,
            'client_ip_address' => $this->client_ip_address,
            'coach_first_name' => $this->coach_first_name,
            'coach_last_name' => $this->coach_last_name,
            'coach_email' =>  $this->coach_email,
            'coach_url' => $this->coach_url,
            'annual_revenue' => $this->annual_revenue,
            'gross_profit_margin' => $this->gross_profit_margin,
            'net_profit_margin' => $this->net_profit_margin,
            'percentage_impact' => $this->percentage_impact,
            'currency' => $this->currency,
            'net_profit' => $this->net_profit,
            'new_annual_profit' => $this->new_annual_profit,
            'cut_costs' => $this->cut_costs,
            'revenueincrease_cut_costs' => $this->revenueincrease_cut_costs,
            'market_dominating_position' => $this->market_dominating_position,
            'revenueincrease_market_dominating_position' => $this->revenueincrease_market_dominating_position,
            'compelling_offer' => $this->compelling_offer,
            'revenueincrease_compelling_offer' => $this->revenueincrease_compelling_offer,
            'increase_prices' => $this->increase_prices,
            'revenueincrease_increase_prices' => $this->revenueincrease_increase_prices,
            'upsell_cross_sell' => $this->upsell_cross_sell,
            'revenueincrease_upsell_cross_sell' => $this->revenueincrease_upsell_cross_sell,
            'bundling' => $this->bundling,
            'revenueincrease_bundling' => $this->revenueincrease_bundling,
            'downsell' => $this->downsell,
            'revenueincrease_downsell' => $this->revenueincrease_downsell,
            'additional_products_services' => $this->additional_products_services,
            'revenueincrease_additional_products_services_revenue' => $this->revenueincrease_additional_products_services_revenue,
            'drip_campaign' => $this->drip_campaign,
            'revenueincrease_drip_campaign' => $this->revenueincrease_drip_campaign,
            'alliances_joint_ventures' => $this->alliances_joint_ventures,
            'revenueincrease_alliances_joint_ventures' => $this->revenueincrease_alliances_joint_ventures,
            'more_leads' => $this->more_leads,
            'revenueincrease_more_leads' => $this->revenueincrease_more_leads,
            'digital_marketing' => $this->digital_marketing,
            'revenueincrease_digital_marketing' => $this->revenueincrease_digital_marketing,
            'content_marketing' => $this->content_marketing,
            'revenueincrease_content_marketing' => $this->revenueincrease_content_marketing,
            'website_optimization' => $this->website_optimization,
            'revenueincrease_website_optimization' => $this->revenueincrease_website_optimization,
            'email_marketing' => $this->email_marketing,
            'revenueincrease_email_marketing' => $this->revenueincrease_email_marketing,
            'search_engine_optimization' => $this->search_engine_optimization,
            'revenueincrease_search_engine_optimization' => $this->revenueincrease_search_engine_optimization,
            'digital_advertising' => $this->digital_advertising,
            'revenueincrease_digital_advertising' => $this->revenueincrease_digital_advertising,
            'social_media' => $this->social_media,
            'revenueincrease_social_media' => $this->revenueincrease_social_media,
            'video_marketing' => $this->video_marketing,
            'revenueincrease_video_marketing' => $this->revenueincrease_video_marketing,
            'metrics_marketing' => $this->metrics_marketing,
            'revenueincrease_metrics_marketing' => $this->revenueincrease_metrics_marketing,
            'strategy' => $this->strategy,
            'revenueincrease_strategy' => $this->revenueincrease_strategy,
            'trust_expertise_education' => $this->trust_expertise_education,
            'revenueincrease_trust_expertise_education' => $this->revenueincrease_trust_expertise_education,
            'policies_procedures' => $this->policies_procedures,
            'revenueincrease_policies_procedures' => $this->revenueincrease_policies_procedures,
            'referral_systems' => $this->referral_systems,
            'revenueincrease_referral_systems' => $this->revenueincrease_referral_systems,
            'publicity_pr' => $this->publicity_pr,
            'revenueincrease_publicity_pr' => $this->revenueincrease_publicity_pr,
            'direct_mail' => $this->direct_mail,
            'revenueincrease_direct_mail' => $this->revenueincrease_direct_mail,
            'advertising' => $this->advertising,
            'revenueincrease_advertising' => $this->revenueincrease_advertising,
            'scripts' => $this->scripts,
            'revenueincrease_scripts' => $this->revenueincrease_scripts,
            'initial_close_rate' => $this->initial_close_rate,
            'revenueincrease_initial_close_rate' => $this->revenueincrease_initial_close_rate,
            'follow_up_close_rate' => $this->follow_up_close_rate,
            'revenueincrease_follow_up_close_rate' => $this->revenueincrease_follow_up_close_rate,
            'sales_team' => $this->sales_team,
            'revenueincrease_sales_team' => $this->revenueincrease_sales_team,
            'more_appointments' => $this->more_appointments,
            'revenueincrease_more_appointments' => $this->revenueincrease_more_appointments,
            'increase_frequency_of_purchase' => $this->increase_frequency_of_purchase,
            'revenueincrease_increase_frequency_of_purchase' => $this->revenueincrease_increase_frequency_of_purchase,
            'increase_longevity_of_buying_relationship' => $this->increase_longevity_of_buying_relationship,
            'revenueincrease_increase_longevity_buying_relationship' => $this->revenueincrease_increase_longevity_buying_relationship,
            'sales_training' => $this->sales_training,
            'revenueincrease_sales_training' => $this->revenueincrease_sales_training,
            'more_profitable_trade_shows' =>$this->more_profitable_trade_shows,
            'revenueincrease_more_profitable_trade_shows' => $this->revenueincrease_more_profitable_trade_shows,
            'dealing_with_decision_makers' => $this->dealing_with_decision_makers,
            'revenueincrease_dealing_with_decision_makers' => $this->revenueincrease_dealing_with_decision_makers,
            'attracting_dream_clients' => $this->attracting_dream_clients,
            'revenueincrease_attracting_dream_clients' => $this->revenueincrease_attracting_dream_clients,
            'order_fullfillment' => $this->order_fullfillment,
            'revenueincrease_order_fullfillment' => $this->revenueincrease_order_fullfillment,
            'overcoming_buyers_remorse' => $this->overcoming_buyers_remorse,
            'revenueincrease_overcoming_buyers_remorse' => $this->revenueincrease_overcoming_buyers_remorse,
            'simulation_date' => $this->simulation_date
            ];
    }
}